"""Add ProductAuditLog Persistent

Revision ID: 272ce6e5e393
Revises: 61927af1a642
Create Date: 2026-03-09 18:00:15.167908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272ce6e5e393'
down_revision: Union[str, Sequence[str], None] = '61927af1a642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('admin_username', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_audit_logs_product_id'), 'product_audit_logs', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_audit_logs_product_id'), table_name='product_audit_logs')
    op.drop_table('product_audit_logs')
    # ### end Alembic commands ###
