"""restore_delivery_date

Revision ID: 4e5006daf388
Revises: 272ce6e5e393
Create Date: 2026-03-11 10:27:49.564441

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e5006daf388"
down_revision: str | Sequence[str] | None = "272ce6e5e393"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offers", sa.Column("delivery_date", sa.Date(), nullable=True))
    # Set default value for existing rows (e.g., today)
    op.execute("UPDATE offers SET delivery_date = CURRENT_DATE WHERE delivery_date IS NULL")
    op.alter_column("offers", "delivery_date", nullable=False)
    op.drop_column("offers", "delivery_days_offset")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column(
            "delivery_days_offset",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("offers", "delivery_date")
    # ### end Alembic commands ###
